name: EnergeticStorage
main: com.liamxsage.energeticstorage.EnergeticStorage
version: ${version}
description: "EnergeticStorage is a plugin for managing energetic storage systems."
author: "LiamXSage"
api-version: "1.20"
loader: com.liamxsage.energeticstorage.DependencyLoader

dependencies:
  server:
    Multiverse-Core:
      required: false
      load: BEFORE
    Lands:
      required: false
      load: BEFORE